### ISSUE TITLE
Bio.Alphabet no longer supported

### ISSUE THREAD

**Issue by yihualiued** [peterculviner/ribodeplete#1]
Hi Peter, 

I am trying to use the code but cannot load the libraries. The error message (see below) suggested the Bio.Alphabet package is no longer supported. Thus I guess the script might need some adaptions according to the change.

Best,
Yihua

> ...../ribodeplete/ribodeplete/ribodeplete/_depletion_functions.py in <module>
>      4 from Bio.SeqUtils.MeltingTemp import Tm_NN as tm
>      5 from Bio.SeqUtils import MeltingTemp as mt
> ----> 6 from Bio.Alphabet.IUPAC import unambiguous_dna, unambiguous_rna
>       7 from Bio.Seq import Seq
>       8 from Bio import SeqIO
> 
> ...../envs/...../lib/python3.9/site-packages/Bio/Alphabet/__init__.py in <module>
>      18 """
>      19 
> ---> 20 raise ImportError(
>      21     "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
>      22 )
>
> ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

**Comment by peterculviner** [comment]
removed these references, should work now!
